# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Build and deploy

on:
  push:
    paths:
      - "**/*.ipynb"
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: lts

      - name: Extract SVG
        run: deno run --allow-read=./ --allow-write=dist/ script/extract-svg.ts dist/

      - name: Create index
        run: deno run --allow-read=dist/ --allow-write=dist/ script/create-index.ts dist/

      - name: Tarball
        run: script/tarball.sh dist/

      - name: Upload dist
        id: deployment
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist/dist.tar.gz
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
